config/routes.rb
Crowded::Application.routes.draw do
  resources :homes

  devise_for :users

  root 'homes#index'

  resources :events

  

end

app/models/event.rb
class Event < ActiveRecord::Base 

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController 
  
  def index
    @events = Event.all
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/events/index.html.erb
<ul>
  <% @events.each do |event| %>
  <li><%= event.title %></li>

<% end %> 
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowded</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <div class="col-md-9">
      <div class="navbar navbar-inverse">
        <div class="navbar-header">
          <ul class="nav">
            <li><%= link_to 'Crowded', homes_path %></li>
            <li><%= link_to 'Events', events_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Sign in', user_session_path %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
      </div>
    </div>
  </div>
</div>


<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

<%= yield %>

</body>
</html>